/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 C:\Users\kembe\Documents\lomba-amikom\public\base.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    model: THREE.Mesh
  }
  materials: {
    place_holder: THREE.MeshStandardMaterial
  }
}

export function Buku(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/base.glb') as GLTFResult
  return (
    <>
      <pointLight intensity={30} />
      <group {...props} dispose={null}>
        <mesh geometry={nodes.model.geometry} material={materials.place_holder} rotation={[Math.PI / 2, 0, 0]} scale={2} />
      </group>
    </>
  )
}

useGLTF.preload('/base.glb')
