/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 C:\Users\kembe\Documents\lomba-amikom\public\3d-asset\rak-sepatu.glb -t 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    model: THREE.Mesh;
  };
  materials: {
    place_holder: THREE.MeshStandardMaterial;
  };
};

export function Bookcase(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/bookcase.glb") as GLTFResult;
  return (
    <>
      <hemisphereLight intensity={2} position={[0, 0, 0]} />
      <group {...props} dispose={null}>
        <mesh
          geometry={nodes.model.geometry}
          material={materials.place_holder}
          scale={4}
        />
      </group>
    </>
  );
}

useGLTF.preload("/bookcase.glb");
