/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 C:\Users\kembe\Documents\lomba-amikom\public\kursi.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    model: THREE.Mesh
  }
  materials: {
    place_holder: THREE.MeshStandardMaterial
  }
}

export function Kursi(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/kursi.glb') as GLTFResult
  return (
    <>
    <hemisphereLight intensity={1} />
    <pointLight intensity={50} position={[1, 5, 1]} />
      <group {...props} dispose={null}>
        <mesh geometry={nodes.model.geometry} material={materials.place_holder} scale={3} />
      </group>
    </>
  )
}

useGLTF.preload('/kursi.glb')
