import type { Metadata } from "next";
import { Roboto_Slab }from "next/font/google";
import "./globals.css";
import Navbar from "./components/layouts/Navbar/page";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Roboto_Slab({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"]
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
