import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/layouts/Navbar/page";
import FooterPage from "./pages/Footer/Footer";
import { CartProvider } from "./context/CartContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`bg-black overflow-x-hidden`}>
        <CartProvider>
          <Navbar />
          {children}
          <FooterPage />  
        </CartProvider>
      </body>
    </html>
  );
}
